language: scala
cache:
  directories:
  - $HOME/.ivy2/cache

  # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
  # which fortunately corresponds to current scalaz settings.
  # The line below can be used to cache a given sbt version.
  # - $HOME/.sbt/launchers/0.13.x

  # The line below is used to cache the scala version used by the build
  # job, as these versions might be replaced after a Travis CI build
  # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
  - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

scala:
  - 2.11.8
  - 2.12.8

jdk:
  - openjdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean scalastyle coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
